# Change these first
owner: mightora # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Mightora.io
    url: https://mightora.io
  - name: TechTweedie
    url: https://techtweedie.github.io
  - name: api.Mightora.io
    url: https://api.mightora.io
assignees: # Users to assign downtime issues (optional)
  - itweedie
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.mightora.io
  # baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/mightora/mightora.io/refs/heads/main/static/safari-pinned-tab.svg
  name: mightora.io status
  introTitle: "**mightora.io status** - The status of our free tools for Power Platform"
  introMessage: This status page provides **real-time** updates on the availability of free tools hosted on [mightora.io](https://mightora.io) for the Power Platform. Powered by GitHub Actions, Issues, and Pages. [**Learn more or get your own**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: Home
      href: https://mightora.io

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
